//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Information_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Library_Information_SystemEntities : DbContext
    {

        private static Library_Information_SystemEntities _instance;
        public static Library_Information_SystemEntities getInstance()
        {
            if (_instance == null)
                _instance = new Library_Information_SystemEntities();
            return _instance;
        }

        private static Library_Information_SystemEntities _context;
        public static Library_Information_SystemEntities GetContext()
        {
            if (_context == null)
                _context = new Library_Information_SystemEntities();
            return _context;
        }

        public Library_Information_SystemEntities()
            : base("name=Library_Information_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Библиотеки> Библиотеки { get; set; }
        public DbSet<Пополнение_фонда> Пополнение_фонда { get; set; }
        public DbSet<Сотрудники> Сотрудники { get; set; }
        public DbSet<Тип_литературы> Тип_литературы { get; set; }
        public DbSet<Фонд_Библиотеки> Фонд_Библиотеки { get; set; }
    }
}
