//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Information_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Библиотеки
    {
        public Библиотеки()
        {
            this.Сотрудники = new HashSet<Сотрудники>();
            this.Фонд_Библиотеки = new HashSet<Фонд_Библиотеки>();
        }
    
        public int BibliotekID { get; set; }
        public string Name_Bib { get; set; }
        public string Adres_Bib { get; set; }
        public string Gorod_Bib { get; set; }
    
        public virtual ICollection<Сотрудники> Сотрудники { get; set; }
        public virtual ICollection<Фонд_Библиотеки> Фонд_Библиотеки { get; set; }
    }
}
