//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Information_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пополнение_фонда
    {
        public int ID { get; set; }
        public int FondID { get; set; }
        public int Sotrudnik_ID { get; set; }
        public string Istoch_lit_Name { get; set; }
        public int Tip_LitID { get; set; }
        public string Izdatelstvo { get; set; }
        public Nullable<int> Data_izdania { get; set; }
        public int Kolvo_ekz { get; set; }
        public string Image { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual Тип_литературы Тип_литературы { get; set; }
        public virtual Фонд_Библиотеки Фонд_Библиотеки { get; set; }

        public string GetProductPhoto
        {
            get
            {
                if (Image != null)
                    return $@"res\{Image}";
                else
                    return null;
            }
        }
    }
}
