//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Information_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        public Сотрудники()
        {
            this.Пополнение_фонда = new HashSet<Пополнение_фонда>();
        }
    
        public int Sotrudnik_ID { get; set; }
        public string Fam_Sotrudn { get; set; }
        public int BibliotekID { get; set; }
        public string Doljnost { get; set; }
        public int God_rojdenia { get; set; }
        public string God_postuprab { get; set; }
        public string Obrazovanie { get; set; }
        public int Zarplata { get; set; }
    
        public virtual Библиотеки Библиотеки { get; set; }
        public virtual ICollection<Пополнение_фонда> Пополнение_фонда { get; set; }
    }
}
