//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Information_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Тип_литературы
    {
        public Тип_литературы()
        {
            this.Пополнение_фонда = new HashSet<Пополнение_фонда>();
        }
    
        public int Tip_LitID { get; set; }
        public string Tip_Lit_Name { get; set; }
    
        public virtual ICollection<Пополнение_фонда> Пополнение_фонда { get; set; }
    }
}
