//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Information_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Фонд_Библиотеки
    {
        public Фонд_Библиотеки()
        {
            this.Пополнение_фонда = new HashSet<Пополнение_фонда>();
        }
    
        public int FondID { get; set; }
        public string Name_Fond { get; set; }
        public int BibliotekID { get; set; }
        public int Kolvo_knig { get; set; }
        public int Kolvo_jurnals { get; set; }
        public int Kolvo_gazet { get; set; }
        public int Kolvo_sborniks { get; set; }
        public int Kolvo_dissert { get; set; }
        public int Kolvo_referats { get; set; }
    
        public virtual Библиотеки Библиотеки { get; set; }
        public virtual ICollection<Пополнение_фонда> Пополнение_фонда { get; set; }
    }
}
